# Generated by Django 4.2.5 on 2023-09-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_person_age_remove_person_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='name',
        ),
    ]
